// <auto-generated />
// This is an empty, temporary enum.
// Please run the binder to generate the contents of this enum.

namespace OrkCore.Graphics.GL
{
    public enum DebugSeverity
    {
    }
}
